name: CI/CD Pipeline

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  lint:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.lint-format.yml
    secrets: inherit

  document:
    needs: lint
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.document.yml
    secrets: inherit
