name: CI/CD Pipeline

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.lint-format.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  document:
    needs: lint
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.document.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
