name: CI/CD Pipeline

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: kurocado-studio/dev-ops/.github/workflows/v1/lint.formatting.yml@main
    secrets: inherit

  document:
    needs: lint
    uses: kurocado-studio/dev-ops/.github/workflows/v1/document.writerside.yml@main
    secrets: inherit
