name: Dependabot Auto-Merge

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR info
        id: pr_info
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

  dependabot-auto-merge:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.dependabot-auto-merge.yml@main
    with:
      PR_NUMBER: ${{ env.PR_NUMBER }}
      PR_URL: ${{ env.PR_URL }}
      PR_AUTHOR: ${{ env.PR_AUTHOR }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
