name: Dependabot Auto-Merge

on:
  workflow_run:
    # Must match the exact name of your CI/CD workflow
    workflows: ['CI/CD Pipeline']
    inputs:
      PR_NUMBER:
        description: 'Pull Request Number'
        required: true
      PR_URL:
        description: 'Pull Request URL'
        required: true
      PR_AUTHOR:
        description: 'Pull Request Author'
        required: true
      GITHUB_TOKEN:
        description: 'GitHub Token'
        required: true
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Set PR Info as Environment Variables
        run: |
          echo "PR_NUMBER=${{ inputs.PR_NUMBER }}" >> $GITHUB_ENV
          echo "PR_URL=${{ inputs.PR_URL }}" >> $GITHUB_ENV
          echo "PR_AUTHOR=${{ inputs.PR_AUTHOR }}" >> $GITHUB_ENV

      - name: Exit if PR was not created by Dependabot
        if: env.PR_AUTHOR != 'dependabot[bot]'
        run: exit 1

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ inputs.GITHUB_TOKEN }}'

      - name: Attempt Squash Merge
        if: success()
        run: |
          gh pr merge "$PR_URL" --squash --merge --auto
        env:
          GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
