name: Dependabot Auto-Merge

on:
  workflow_run:
    # Must match the exact name of your CI/CD workflow
    workflows: ['CI/CD Pipeline']
    inputs:
      GITHUB_EVENT:
        description: 'GitHub Event Object'
        required: true
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Parse GitHub Event
        id: parse_event
        run: |
          echo "GITHUB_EVENT_JSON=${{ inputs.GITHUB_EVENT }}" >> $GITHUB_ENV
          # Parse the JSON string into variables you need
          PR_NUMBER=$(echo ${{ inputs.GITHUB_EVENT }} | jq -r '.pull_request.number')
          PR_URL=$(echo ${{ inputs.GITHUB_EVENT }} | jq -r '.pull_request.html_url')
          PR_AUTHOR=$(echo ${{ inputs.GITHUB_EVENT }} | jq -r '.pull_request.user.login')

          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV

      - name: Exit if PR was not created by Dependabot
        if: env.PR_AUTHOR != 'dependabot[bot]'
        run: exit 1

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Attempt Squash Merge
        if: success()
        run: |
          gh pr merge "$PR_URL" --squash --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
