name: Dependabot Auto-Merge

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'

    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint
        uses: kurocado-studio/dev-ops/.github/actions/lint@main

      - name: Test
        uses: kurocado-studio/dev-ops/.github/actions/test@main

      - name: Build
        run: pnpm build

      - name: Attempt Squash Merge
        if: success()
        run: gh pr merge --squash "$PR_URL" --merge --auto
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
